### ISSUE TITLE
MatadataModule in same folder

### ISSUE THREAD

**Issue by dangarp** [HackandCraft/Nancy.Metadata.Swagger#2]
The class for documenting does not only have to follow the namestandard xxMetdataModel but also reside in same directory which is not mentioned in description.

**Comment by JordiCamps** [comment]
??

El Dt, 1 Des., 2015 15.32 dangarp <notifications@github.com> va escriure:

**Comment by envilogger** [comment]
Thanks for your response, I added this info to readme
